// <auto-generated />
using CRUD_PeriferiaIT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRUD_PeriferiaIT.Migrations
{
    [DbContext(typeof(ViajesContext))]
    [Migration("20210924165615_CrearInicial")]
    partial class CrearInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CRUD_PeriferiaIT.Models.Empleados", b =>
                {
                    b.Property<int>("EmpleadosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellido")
                        .HasColumnType("varchar(100)");

                    b.Property<long>("Identificacion")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(100)");

                    b.HasKey("EmpleadosID");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("CRUD_PeriferiaIT.Models.Viajes", b =>
                {
                    b.Property<int>("ViajesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Destino")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("EmpleadosID")
                        .HasColumnType("int");

                    b.Property<string>("HoraViaje")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombrePasajero")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Origen")
                        .HasColumnType("varchar(100)");

                    b.Property<float>("TiempoViaje")
                        .HasColumnType("float(1)");

                    b.Property<int>("Vehiculo")
                        .HasColumnType("int");

                    b.HasKey("ViajesID");

                    b.HasIndex("EmpleadosID");

                    b.ToTable("Viajes");
                });

            modelBuilder.Entity("CRUD_PeriferiaIT.Models.Viajes", b =>
                {
                    b.HasOne("CRUD_PeriferiaIT.Models.Empleados", "Empleados")
                        .WithMany()
                        .HasForeignKey("EmpleadosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
